---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: java-app
  namespace: openshift
  labels:
    pipeline.openshift.io/runtime: java
    pipeline.openshift.io/type: kubernetes
spec:
  description: >-
    The Pipline to buld and deploy the Hello Tekton Java App https://github.com/JonkeyGuan/tekton-demo as a deployment.
  params:
    - name: IMAGE_NAME
      description: >-
        The fully qualified image name e.g example.com/tekton-demo/tekton-demo
      default: image-registry.openshift-image-registry.svc:5000/tekton-demo/tekton-demo:latest
    - name: APP_NAME
      description: The app name
    - name: GITHUB_REPO_URL
      description: The GitHub Repo of the Java Application
      default: https://github.com/JonkeyGuan/tekton-demo
    - name: GITHUB_REPO_REVISION
      description: The GitHub revision to use
      default: main
  workspaces:
    - name: source
  tasks:
    - name: clone-sources
      params:
        - name: url
          value: $(params.GITHUB_REPO_URL)
        - name: revision
          value: $(params.GITHUB_REPO_REVISION)
        - name: deleteExisting
          value: 'true'
        - name: subdirectory
          value: $(params.APP_NAME)
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: source
    - name: build-test
      params:
        - name: GOALS
          value:
            - clean
            - test
        - name: SUB_DIR
          value: $(params.APP_NAME)
      runAfter:
        - clone-sources
      taskRef:
        kind: ClusterTask
        name: mvn
      workspaces:
        - name: source
          workspace: source
    - name: build-binary
      params:
        - name: GOALS
          value:
            - '-DskipTests'
            - clean
            - package
        - name: SUB_DIR
          value: $(params.APP_NAME)
      runAfter:
        - build-test
      taskRef:
        kind: ClusterTask
        name: mvn
      workspaces:
        - name: source
          workspace: source
    - name: build-image
      params:
        - name: IMAGE
          value: $(params.IMAGE_NAME)
        - name: TLSVERIFY
          value: 'false'
        - name: CONTEXT
          value: $(params.APP_NAME)
      runAfter:
        - build-binary
      taskRef:
        kind: ClusterTask
        name: buildah
      workspaces:
        - name: source
          workspace: source
    - name: apply-manifests
      params:
        - name: sub_dir
          value: $(params.APP_NAME)
      runAfter:
        - build-image
      taskRef:
        kind: ClusterTask
        name: apply-manifests
      workspaces:
        - name: source
          workspace: source
    - name: update-deployment
      params:
        - name: deployment
          value: $(params.APP_NAME)
        - name: IMAGE
          value: $(params.IMAGE_NAME)@$(tasks.build-image.results.IMAGE_DIGEST)
      runAfter:
        - apply-manifests
      taskRef:
        kind: ClusterTask
        name: update-deployment
