apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: tekton-demo
spec:
  params:
  - name: GITHUB_REPO_URL
    value: $(body.repository.url)
  - name: APP_NAME
    value: $(body.repository.name)
  - name: GITHUB_REPO_REVISION
    value: $(body.head_commit.id)
